In [3]:
import pandas as pd

data = pd.read_csv("fraudTrain.csv")
data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81703 entries, 0 to 81702
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             81703 non-null  int64
 1   trans_date_trans_time  81703 non-null  object
 2   cc_num                 81703 non-null  int64
 3   merchant               81703 non-null  object
 4   category               81703 non-null  object
 5   amt                    81703 non-null  float64
 6   first                  81703 non-null  object
 7   last                   81703 non-null  object
 8   gender                 81703 non-null  object
 9   street                 81703 non-null  object
 10  city                   81703 non-null  object
 11  state                  81703 non-null  object
 12  zip                    81703 non-null  int64
 13  lat                    81703 non-null  float64
 14  long                   81703 non-null  float64
 15  city_pop               81703 non-null  int64
 16  job                    81702 non-null  object
 17  dob                    81702 non-null  object
 18  trans_num              81702 non-null  object
 19  unix_time              81702 non-null  float64
 20  merch_lat              81702 non-null  float64
 21  merch_long             81702 non-null  float64
 22  is_fraud               81702 non-null  float64
dtypes: float64(7), int64(4), object(12)
memory usage: 14.3+ MB

In [5]:
data.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,81703.000000,8.170300e+04,81703.000000,81703.000000,81703.000000,81703.000000,8.170300e+04,8.170200e+04,81702.000000,81702.000000,81702.000000
mean,40851.000000,4.198167e+17,72.020171,48750.463251,38.540303,-90.207547,8.979300e+04,1.327455e+09,38.540864,-90.209024,0.009816
std,23585.768859,1.311997e+18,149.924767,26922.422403,5.071784,13.821681,3.031172e+05,1.194827e+06,5.104599,13.834769,0.098590
min,0.000000,6.041621e+10,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.325376e+09,19.040141,-166.670132,0.000000
25%,20425.500000,1.800429e+14,9.690000,26041.000000,34.668900,-96.790900,7.430000e+02,1.326452e+09,34.773376,-96.872814,0.000000
50%,40851.000000,3.519607e+15,47.990000,48174.000000,39.354300,-87.461600,2.456000e+03,1.327457e+09,39.369744,-87.407418,0.000000
75%,61276.500000,4.642255e+15,83.830000,72011.000000,41.846700,-80.128400,2.047800e+04,1.328457e+09,41.927733,-80.182705,0.000000
max,81702.000000,4.992346e+18,12788.070000,99783.000000,65.689900,-67.950300,2.906700e+06,1.329531e+09,66.659242,-66.967742,1.000000

In [6]:
data['is_fraud'].value_counts()

is_fraud
0.0    80900
1.0      802
Name: count, dtype: int64

In [7]:
data = data.drop([
'trans_date_trans_time','cc_num','merchant','category','first','last',
'street','city','state','zip','dob','trans_num'
], axis=1)

In [8]:
data.head()

,Unnamed: 0,amt,gender,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud
0,0,4.97,F,36.0788,-81.1781,3495,"Psychologist, counselling",1.325376e+09,36.011293,-82.048315,0.0
1,1,107.23,F,48.8878,-118.2105,149,Special educational needs teacher,1.325376e+09,49.159047,-118.186462,0.0
2,2,220.11,M,42.1808,-112.2620,4154,Nature conservation officer,1.325376e+09,43.150704,-112.154481,0.0
3,3,45.00,M,46.2306,-112.1138,1939,Patent attorney,1.325376e+09,47.034331,-112.561071,0.0
4,4,41.96,M,38.4207,-79.4629,99,Dance movement psychotherapist,1.325376e+09,38.674999,-78.632459,0.0

In [9]:
X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

In [10]:
X.shape

(81703, 10)

In [11]:
y.shape

(81703,)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
X_train.shape

(65362, 10)

In [15]:
X_test.shape

(16341, 10)

In [16]:
from sklearn.linear_model import LogisticRegression

In [18]:
X = pd.get_dummies(X)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
X = X.fillna(0)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [24]:
data = data.dropna()

In [25]:
X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

In [26]:
X = pd.get_dummies(X)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [29]:
y_pred = model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9887399791934398
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99     16180
         1.0       0.04      0.01      0.01       161

    accuracy                           0.99     16341
   macro avg       0.52      0.50      0.50     16341
weighted avg       0.98      0.99      0.98     16341