In [17]:
import pandas as pd
import numpy as np

In [18]:
data = pd.read_csv("fraudTrain.csv")
data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2.703186e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495.0,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,6.304233e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149.0,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,3.885949e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154.0,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3.534094e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939.0,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,3.755342e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99.0,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918328 entries, 0 to 918327
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             918328 non-null  int64
 1   trans_date_trans_time  918327 non-null  object
 2   cc_num                 918327 non-null  float64
 3   merchant               918327 non-null  object
 4   category               918327 non-null  object
 5   amt                    918327 non-null  float64
 6   first                  918327 non-null  object
 7   last                   918327 non-null  object
 8   gender                 918327 non-null  object
 9   street                 918327 non-null  object
 10  city                   918327 non-null  object
 11  state                  918327 non-null  object
 12  zip                    918327 non-null  float64
 13  lat                    918327 non-null  float64
 14  long                   918327 non-null  float64
 15  city_pop               918327 non-null  float64
 16  job                    918327 non-null  object
 17  dob                    918327 non-null  object
 18  trans_num              918327 non-null  object
 19  unix_time              918327 non-null  float64
 20  merch_lat              918327 non-null  float64
 21  merch_long             918327 non-null  float64
 22  is_fraud               918327 non-null  float64
dtypes: float64(10), int64(1), object(12)
memory usage: 161.1+ MB

In [20]:
data.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,918328.000000,9.183270e+05,918327.000000,918327.000000,918327.000000,918327.000000,9.183270e+05,9.183270e+05,918327.000000,918327.000000,918327.000000
mean,459163.500000,4.166811e+17,70.251291,48799.711225,38.534055,-90.228488,8.911297e+04,1.342772e+09,38.533847,-90.228595,0.005635
std,265098.603341,1.308242e+18,161.391022,26905.738398,5.076314,13.768725,3.025284e+05,9.032144e+06,5.110674,13.780791,0.074857
min,0.000000,6.041621e+10,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.325376e+09,19.027785,-166.671242,0.000000
25%,229581.750000,1.800400e+14,9.640000,26237.000000,34.620500,-96.798000,7.430000e+02,1.335433e+09,34.734585,-96.903219,0.000000
50%,459163.500000,3.520550e+15,47.440000,48174.000000,39.354300,-87.476900,2.456000e+03,1.342920e+09,39.364013,-87.436174,0.000000
75%,688745.250000,4.642255e+15,83.070000,72042.000000,41.894800,-80.158000,2.047800e+04,1.350766e+09,41.954361,-80.226991,0.000000
max,918327.000000,4.992346e+18,28948.900000,99783.000000,66.693300,-67.950300,2.906700e+06,1.356868e+09,67.510267,-66.956540,1.000000

In [21]:
data['is_fraud'].value_counts()

is_fraud
0.0    913152
1.0      5175
Name: count, dtype: int64

In [22]:
data = data.drop([
'trans_date_trans_time','cc_num','merchant','category','first','last',
'street','city','state','zip','dob','trans_num'
], axis=1)

In [23]:
data.head()

,Unnamed: 0,amt,gender,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud
0,0,4.97,F,36.0788,-81.1781,3495.0,"Psychologist, counselling",1.325376e+09,36.011293,-82.048315,0.0
1,1,107.23,F,48.8878,-118.2105,149.0,Special educational needs teacher,1.325376e+09,49.159047,-118.186462,0.0
2,2,220.11,M,42.1808,-112.2620,4154.0,Nature conservation officer,1.325376e+09,43.150704,-112.154481,0.0
3,3,45.00,M,46.2306,-112.1138,1939.0,Patent attorney,1.325376e+09,47.034331,-112.561071,0.0
4,4,41.96,M,38.4207,-79.4629,99.0,Dance movement psychotherapist,1.325376e+09,38.674999,-78.632459,0.0

In [24]:
data = data.dropna()

In [25]:
X = data.drop('is_fraud', axis=1)
y = data['is_fraud']

In [26]:
X = pd.get_dummies(X)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [30]:
y_pred = model.predict(X_test)

In [32]:
import warnings
warnings.filterwarnings('ignore')

In [33]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9944192174926225
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00    182641
         1.0       0.00      0.00      0.00      1025

    accuracy                           0.99    183666
   macro avg       0.50      0.50      0.50    183666
weighted avg       0.99      0.99      0.99    183666